// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Router from "next/router";
import * as MainLayout$RescriptNextjsTemplate from "./layouts/MainLayout.bs.js";

function $$default(props) {
  var router = Router.useRouter();
  var content = React.createElement(props.Component, props.pageProps);
  var match = router.route;
  if (match === "/examples") {
    return React.createElement(MainLayout$RescriptNextjsTemplate.make, {
                children: null
              }, React.createElement("h1", {
                    className: "font-bold"
                  }, "Examples Section"), React.createElement("div", undefined, content));
  } else {
    return React.createElement(MainLayout$RescriptNextjsTemplate.make, {
                children: content
              });
  }
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
