// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ResultRowAdding$Web from "./ResultRowAdding.bs.js";

function AddResultRow(Props) {
  var state = Props.state;
  var dispatch = Props.dispatch;
  React.useState(function () {
        return false;
      });
  var match = state.mode;
  if (match === 0) {
    return React.createElement(ResultRowAdding$Web.make, {
                dispatch: dispatch
              });
  } else {
    return null;
  }
}

var make = AddResultRow;

export {
  make ,
  
}
/* react Not a pure module */
