// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as State$Web from "./State.bs.js";
import * as Reducer$Web from "./Reducer.bs.js";
import * as ResultTable$Web from "./ResultTable.bs.js";

function App(Props) {
  var match = React.useReducer(Reducer$Web.reducer, State$Web.initialState);
  var state = match[0];
  console.log(state);
  return React.createElement(ResultTable$Web.make, {
              state: state,
              dispatch: match[1]
            });
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
