// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function onChangeName($$event) {
  return $$event.currentTarget.value;
}

function onChangeScore($$event) {
  var value = Belt_Option.getWithDefault(Belt_Int.fromString($$event.currentTarget.value), 0);
  if (value < 0) {
    return 0;
  } else {
    return value;
  }
}

export {
  onChangeName ,
  onChangeScore ,
  
}
/* No side effect */
