// Generated by ReScript, PLEASE EDIT WITH CARE


var AddCircleIcon;

var AddCircleOutlineIcon;

var CancelIcon;

var EditIcon;

var DeleteIcon;

var CheckCircleIcon;

export {
  AddCircleIcon ,
  AddCircleOutlineIcon ,
  CancelIcon ,
  EditIcon ,
  DeleteIcon ,
  CheckCircleIcon ,
  
}
/* No side effect */
