// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core from "@material-ui/core";
import * as AddResultControl$Web from "./AddResultControl.bs.js";

function ResultHeaderShowing(Props) {
  var state = Props.state;
  var dispatch = Props.dispatch;
  return React.createElement(Core.TableHead, {
              children: React.createElement(Core.TableRow, {
                    children: null
                  }, React.createElement(Core.TableCell, {
                        align: "right",
                        children: "Rank",
                        style: {
                          minWidth: "100px"
                        }
                      }), React.createElement(Core.TableCell, {
                        children: "Name",
                        style: {
                          width: "100%"
                        }
                      }), React.createElement(Core.TableCell, {
                        align: "right",
                        children: "Score",
                        style: {
                          minWidth: "100px"
                        }
                      }), React.createElement(Core.TableCell, {
                        children: React.createElement(AddResultControl$Web.make, {
                              state: state,
                              dispatch: dispatch
                            }),
                        style: {
                          minWidth: "100px"
                        }
                      }))
            });
}

var make = ResultHeaderShowing;

export {
  make ,
  
}
/* react Not a pure module */
