// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Core from "@material-ui/core";
import Edit from "@material-ui/icons/Edit";
import Delete from "@material-ui/icons/Delete";

function ResultRowShowing(Props) {
  var result = Props.result;
  var rank = Props.rank;
  var state = Props.state;
  var dispatch = Props.dispatch;
  var disabled = state.mode !== /* Showing */1;
  return React.createElement(Core.TableRow, {
              children: null
            }, React.createElement(Core.TableCell, {
                  align: "right",
                  children: rank.toString()
                }), React.createElement(Core.TableCell, {
                  children: result.name
                }), React.createElement(Core.TableCell, {
                  align: "right",
                  children: result.score.toString()
                }), React.createElement(Core.TableCell, {
                  children: React.createElement("div", undefined, React.createElement(Core.IconButton, {
                            onClick: (function (param) {
                                return Curry._1(dispatch, {
                                            TAG: /* EditMode */3,
                                            _0: result
                                          });
                              }),
                            children: React.createElement(Edit, {}),
                            color: "primary",
                            disabled: disabled
                          }), React.createElement(Core.IconButton, {
                            onClick: (function (param) {
                                return Curry._1(dispatch, {
                                            TAG: /* RemoveResult */2,
                                            _0: result
                                          });
                              }),
                            children: React.createElement(Delete, {}),
                            color: "primary",
                            disabled: disabled
                          }))
                }));
}

var make = ResultRowShowing;

export {
  make ,
  
}
/* react Not a pure module */
