// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ResultHeaderAdding$Web from "./ResultHeaderAdding.bs.js";
import * as ResultHeaderShowing$Web from "./ResultHeaderShowing.bs.js";

function ResultHeader(Props) {
  var state = Props.state;
  var dispatch = Props.dispatch;
  React.useState(function () {
        return false;
      });
  var match = state.mode;
  if (match === 0) {
    return React.createElement(ResultHeaderAdding$Web.make, {
                state: state,
                dispatch: dispatch
              });
  } else {
    return React.createElement(ResultHeaderShowing$Web.make, {
                state: state,
                dispatch: dispatch
              });
  }
}

var make = ResultHeader;

export {
  make ,
  
}
/* react Not a pure module */
