// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Id from "rescript/lib/es6/belt_Id.js";
import * as Belt_Map from "rescript/lib/es6/belt_Map.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";

function cmp(param, param$1) {
  var x = Caml_obj.caml_compare(param[1], param$1[1]);
  if (x !== 0) {
    return -x | 0;
  } else {
    return Caml_obj.caml_compare(param[0], param$1[0]);
  }
}

var ComparableResult = Belt_Id.MakeComparable({
      cmp: cmp
    });

var initialState_results = Belt_Map.make(ComparableResult);

var initialState = {
  results: initialState_results,
  mode: /* Showing */1
};

export {
  ComparableResult ,
  initialState ,
  
}
/* ComparableResult Not a pure module */
