// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function App$app(Props) {
  return React.createElement("div", undefined, "Let's get schwifty!");
}

var app = App$app;

export {
  app ,
  
}
/* react Not a pure module */
