// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as SchwiftyVideo$Web from "./SchwiftyVideo.bs.js";
import * as SchwiftySelector$Web from "./SchwiftySelector.bs.js";

function App(Props) {
  var match = React.useState(function () {
        return false;
      });
  if (match[0]) {
    return React.createElement(SchwiftyVideo$Web.make, {});
  }
  var showVideo = match[1];
  return React.createElement(SchwiftySelector$Web.make, {
              onClick: (function (param) {
                  return Curry._1(showVideo, (function (param) {
                                return true;
                              }));
                })
            });
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
