// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Core from "@material-ui/core";
import MusicVideo from "@material-ui/icons/MusicVideo";

function SchwiftySelector(Props) {
  var onClick = Props.onClick;
  return React.createElement("div", undefined, React.createElement("div", undefined, "Let's get schwifty!"), React.createElement(Core.IconButton, {
                  onClick: (function (param) {
                      return Curry._1(onClick, undefined);
                    }),
                  children: React.createElement(MusicVideo, {}),
                  color: "primary"
                }));
}

var make = SchwiftySelector;

export {
  make ,
  
}
/* react Not a pure module */
