// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import ReactPlayer from "react-player";

function SchwiftyVideo(Props) {
  return React.createElement(ReactPlayer, {
              url: "https://youtu.be/n4Xp6g-_UUw",
              playing: true,
              width: "100%",
              height: "100%"
            });
}

var make = SchwiftyVideo;

export {
  make ,
  
}
/* react Not a pure module */
